/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetCompanyIdRouteImport } from './routes/widget.$companyId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDiagnoseRouteImport } from './routes/_authenticated/diagnose'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads/$leadId'
import { Route as ApiPublicWidgetChatRouteImport } from './routes/api/public/widget.chat'
import { Route as ApiPublicEmailUnsubscribeRouteImport } from './routes/api/public/email.unsubscribe'
import { Route as ApiInternalFollowupsProcessRouteImport } from './routes/api/internal/followups.process'
import { Route as ApiInternalEmailResendWebhookRouteImport } from './routes/api/internal/email.resend.webhook'
import { Route as ApiInternalEmailResendInboundRouteImport } from './routes/api/internal/email.resend.inbound'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetCompanyIdRoute = WidgetCompanyIdRouteImport.update({
  id: '/widget/$companyId',
  path: '/widget/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnoseRoute = AuthenticatedDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWidgetChatRoute = ApiPublicWidgetChatRouteImport.update({
  id: '/api/public/widget/chat',
  path: '/api/public/widget/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailUnsubscribeRoute =
  ApiPublicEmailUnsubscribeRouteImport.update({
    id: '/api/public/email/unsubscribe',
    path: '/api/public/email/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalFollowupsProcessRoute =
  ApiInternalFollowupsProcessRouteImport.update({
    id: '/api/internal/followups/process',
    path: '/api/internal/followups/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalEmailResendWebhookRoute =
  ApiInternalEmailResendWebhookRouteImport.update({
    id: '/api/internal/email/resend/webhook',
    path: '/api/internal/email/resend/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalEmailResendInboundRoute =
  ApiInternalEmailResendInboundRouteImport.update({
    id: '/api/internal/email/resend/inbound',
    path: '/api/internal/email/resend/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impressum': typeof ImpressumRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/widget/$companyId': typeof WidgetCompanyIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/internal/followups/process': typeof ApiInternalFollowupsProcessRoute
  '/api/public/email/unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/internal/email/resend/inbound': typeof ApiInternalEmailResendInboundRoute
  '/api/internal/email/resend/webhook': typeof ApiInternalEmailResendWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impressum': typeof ImpressumRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/widget/$companyId': typeof WidgetCompanyIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/api/internal/followups/process': typeof ApiInternalFollowupsProcessRoute
  '/api/public/email/unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/internal/email/resend/inbound': typeof ApiInternalEmailResendInboundRoute
  '/api/internal/email/resend/webhook': typeof ApiInternalEmailResendWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impressum': typeof ImpressumRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnose': typeof AuthenticatedDiagnoseRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/widget/$companyId': typeof WidgetCompanyIdRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/internal/followups/process': typeof ApiInternalFollowupsProcessRoute
  '/api/public/email/unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/internal/email/resend/inbound': typeof ApiInternalEmailResendInboundRoute
  '/api/internal/email/resend/webhook': typeof ApiInternalEmailResendWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/demo'
    | '/forgot-password'
    | '/impressum'
    | '/reset-password'
    | '/sitemap.xml'
    | '/analytics'
    | '/appointments'
    | '/conversations'
    | '/dashboard'
    | '/diagnose'
    | '/settings'
    | '/widget/$companyId'
    | '/leads/$leadId'
    | '/admin/'
    | '/leads/'
    | '/api/internal/followups/process'
    | '/api/public/email/unsubscribe'
    | '/api/public/widget/chat'
    | '/api/internal/email/resend/inbound'
    | '/api/internal/email/resend/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/demo'
    | '/forgot-password'
    | '/impressum'
    | '/reset-password'
    | '/sitemap.xml'
    | '/analytics'
    | '/appointments'
    | '/conversations'
    | '/dashboard'
    | '/diagnose'
    | '/settings'
    | '/widget/$companyId'
    | '/leads/$leadId'
    | '/admin'
    | '/leads'
    | '/api/internal/followups/process'
    | '/api/public/email/unsubscribe'
    | '/api/public/widget/chat'
    | '/api/internal/email/resend/inbound'
    | '/api/internal/email/resend/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/datenschutz'
    | '/demo'
    | '/forgot-password'
    | '/impressum'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/appointments'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnose'
    | '/_authenticated/settings'
    | '/widget/$companyId'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/admin/'
    | '/_authenticated/leads/'
    | '/api/internal/followups/process'
    | '/api/public/email/unsubscribe'
    | '/api/public/widget/chat'
    | '/api/internal/email/resend/inbound'
    | '/api/internal/email/resend/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImpressumRoute: typeof ImpressumRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WidgetCompanyIdRoute: typeof WidgetCompanyIdRoute
  ApiInternalFollowupsProcessRoute: typeof ApiInternalFollowupsProcessRoute
  ApiPublicEmailUnsubscribeRoute: typeof ApiPublicEmailUnsubscribeRoute
  ApiPublicWidgetChatRoute: typeof ApiPublicWidgetChatRoute
  ApiInternalEmailResendInboundRoute: typeof ApiInternalEmailResendInboundRoute
  ApiInternalEmailResendWebhookRoute: typeof ApiInternalEmailResendWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$companyId': {
      id: '/widget/$companyId'
      path: '/widget/$companyId'
      fullPath: '/widget/$companyId'
      preLoaderRoute: typeof WidgetCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnose': {
      id: '/_authenticated/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof AuthenticatedDiagnoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/widget/chat': {
      id: '/api/public/widget/chat'
      path: '/api/public/widget/chat'
      fullPath: '/api/public/widget/chat'
      preLoaderRoute: typeof ApiPublicWidgetChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/unsubscribe': {
      id: '/api/public/email/unsubscribe'
      path: '/api/public/email/unsubscribe'
      fullPath: '/api/public/email/unsubscribe'
      preLoaderRoute: typeof ApiPublicEmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/followups/process': {
      id: '/api/internal/followups/process'
      path: '/api/internal/followups/process'
      fullPath: '/api/internal/followups/process'
      preLoaderRoute: typeof ApiInternalFollowupsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/email/resend/webhook': {
      id: '/api/internal/email/resend/webhook'
      path: '/api/internal/email/resend/webhook'
      fullPath: '/api/internal/email/resend/webhook'
      preLoaderRoute: typeof ApiInternalEmailResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/email/resend/inbound': {
      id: '/api/internal/email/resend/inbound'
      path: '/api/internal/email/resend/inbound'
      fullPath: '/api/internal/email/resend/inbound'
      preLoaderRoute: typeof ApiInternalEmailResendInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnoseRoute: typeof AuthenticatedDiagnoseRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnoseRoute: AuthenticatedDiagnoseRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImpressumRoute: ImpressumRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WidgetCompanyIdRoute: WidgetCompanyIdRoute,
  ApiInternalFollowupsProcessRoute: ApiInternalFollowupsProcessRoute,
  ApiPublicEmailUnsubscribeRoute: ApiPublicEmailUnsubscribeRoute,
  ApiPublicWidgetChatRoute: ApiPublicWidgetChatRoute,
  ApiInternalEmailResendInboundRoute: ApiInternalEmailResendInboundRoute,
  ApiInternalEmailResendWebhookRoute: ApiInternalEmailResendWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
