/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWidgetChatRouteImport } from './routes/api/widget.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetChatRoute = ApiWidgetChatRouteImport.update({
  id: '/api/widget/chat',
  path: '/api/widget/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/widget/chat': typeof ApiWidgetChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/widget/chat': typeof ApiWidgetChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/widget/chat': typeof ApiWidgetChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/widget/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/widget/chat'
  id: '__root__' | '/' | '/api/widget/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWidgetChatRoute: typeof ApiWidgetChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/chat': {
      id: '/api/widget/chat'
      path: '/api/widget/chat'
      fullPath: '/api/widget/chat'
      preLoaderRoute: typeof ApiWidgetChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWidgetChatRoute: ApiWidgetChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
